/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DanWilkerson' at '9/12/16 11:08 AM' with Gradle 3.0
 *
 * @author DanWilkerson, @date 9/12/16 11:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
